/*
   Copyright 2024 Oscar Pernia

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package main

import (
	"log"
	"os"

	"github.com/otaxhu/goyp/internal/cmd/build"
)

func main() {
	log.SetFlags(0)
	log.SetPrefix("goyp: ")

	if len(os.Args) < 2 {
		os.Stderr.WriteString(`Usage: goyp <command> [arguments...]

Description:
  goyp is a build system for Golang that allows you to compile your code, with support for
  Golang binary dependencies and Go Modules.

  It uses the Go toolchain ('go' command) to perform all of the low level details. So it's required
  to be installed and available in PATH environment variable.

Commands:
  build     Compile the specified Go Module, outputing a zipfile containing all of the binary code
            generated from a non-main package, outputs a executable if it's main package.

  dist-lib  Decompress zipfile generated by 'build', to distribute your library through Go Modules.

  help      Prints help about the different commands.

  install   Install main package to $GOPATH/bin or $HOME/go/bin if $GOPATH is not specified

  run       Build and run the specified Go main package.

  version   Display the current version of goyp.

See 'goyp help' for more information.
`)
		os.Exit(1)
	}

	command := os.Args[1]

	switch command {
	case "run", "version", "help", "dist-lib", "install":
		log.Fatalf("TODO: '%s' command unimplemented", command)
	case "build":
		build.Build(os.Args[2:])
	default:
		log.Fatalf("invalid '%s' command", command)
	}
}
